
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-storage-server
  labels:
    app: base-storage-server
    version: v1
  namespace: xmc-base
spec:
  replicas: 4
  selector:
    matchLabels:
        app: base-storage-server
  template:
    metadata:
      labels:
        app: base-storage-server
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: base-storage-server
        image: docker.dm-ai.cn/xmc-base/base-storage-server:test-14-bcedf317dd161d64c2ca35c9af793c59702abb60-test
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: APOLLO_ENV
          value: TEST
        - name: APOLLO_CONFIG_ADDRESS
          value: http://test-conf.apollo.cc.dm-ai.cn
        - name: APOLLO_CLUSTER_NAME
          value: default
        - name: APOLLO_NAMESPACE
          value: application
        - name: APP_NAME
          value: base-storage-server
        - name: DEPLOY_ENV
          value: test
        - name: APP_NAMESPACE
          value: xmc-base
        - name: aliyun_logs_k8s-test-xmc-base
          value: stdout
      volumeMounts:
      - name: volumName-0
        mountPath: /data1
      volumeMounts:
      - name: volumName-1
        mountPath: data2
        ports:
        - containerPort: 8081
        - containerPort: 8082
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 40
          failureThreshold: 40
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 2000m
            memory: 6000Mi
          limits:
            cpu: 2000m
            memory: 8000Mi
      volumes:
      - name: volumName-0
        persistentVolumeClaim:
          claimName:mypvc1
      - name: volumName-1
        persistentVolumeClaim:
          claimName:mypvc2
