## start domain
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-to-https
  namespace: xmc-base
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: base-storage-server
  namespace: xmc-base
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`base-storage-server.xmc-base.test.dm-ai.cn`)
    kind: Rule
    services:
    - name: base-storage-server
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: base-storage-server-https
  namespace: xmc-base
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`base-storage-server.xmc-base.test.dm-ai.cn`)
    kind: Rule
    services:
    - name: base-storage-server
      namespace: xmc-base
      port: 80
  tls:
    secretName: https-key-secret-test
## end domain