
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: base-storage-server
  name: base-storage-server
  namespace: xmc-base
spec:
  ports:
  - port: 8081
    name: port-8081
    targetPort: 8081
  - port: 8082
    name: port-8082
    targetPort: 8082
  selector:
    app: base-storage-server
  type: ClusterIP