
---
apiVersion: v1
kind: Secret
metadata:
  name: https-key-secret-test
  namespace: xmc-base
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdJakNDQlFxZ0F3SUJBZ0lRREfgsdfgYwOXIwVVdCamc0M0JkQl**********
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBbTgdfgdfNKMkhhUU5xT1VXVlNxal*********